### ISSUE TITLE
QST: solara usage with Treeview

### ISSUE THREAD

**Issue by gab23r** [widgetti/solara#204]
First of all, thanks a lot for building this library. I really think the python community needs this.
I worked a lot with ipyvuetify, for my next application I am trying to used solara. 

In this application I need to interact with a Treeview and I did not make it work with solara yet.
Basically I am trying to make something like this with `rw.Treeview` but I am missing the `on_event` function

```python
import ipyvuetify as v
items = [{'id' : 'a', 'name': 'A'}, {'id' : 'b', 'name': 'B'}]

class my_app(v.Col):    
    def __init__(self):
        self.ipyvuetify_tree = v.Treeview(active = [], items = items, activatable=True)
        self.text = v.Text(children = ['{}'])

        self.ipyvuetify_tree.on_event('update:active', self.update_active)
        
        super().__init__(
            children=[self.ipyvuetify_tree, self.text]
        )
        
    def update_active(self, widget, event, data):
        widget.active = data if data else []
        self.text.children = [f'{data}']

```

Can you give me hints on how to use the `active` trait of `Treeview` ? Thanks !

**Comment by maartenbreddels** [comment]
> First of all, thanks a lot for building this library. I really think the python community needs this.

Thank you, fully agree :)

If you know ipyvuetify, I think the button examples will explain how to add events using the `use_event` hook: https://github.com/widgetti/solara/blob/1c75b62f06bcff92dca60b799f0fd39bd3b7e2bc/solara/components/button.py#L76

I'm a bit reluctant to add this to the solara documentation right now, since it's a bit of an advanced feature, so for now this example will have to do.

Does this help you?

Regards,

Maarten

**Comment by gab23r** [comment]
I did not have the time to test it, I come back to you when I will try this. Thanks a lot

**Comment by maartenbreddels** [comment]
You didn't need to have 2 components, but I think in this case it's a good idea because if you want to make it conditional with the hook (use_event), reacton will complain.

**Comment by gab23r** [comment]
Thanks @maartenbreddels
