### ISSUE TITLE
Components appear to be loaded in duplicate

### ISSUE THREAD

**Issue by mjgorman** [widgetti/solara#331]
Version: `solara==1.22.0`

When attempting to troubleshoot some things I dropped a few print statements into a component which revealed that they were being run multiple times on the first page load which seemed strange to me. If there is anything blocking it doubles the blocking time.

Example to reproduce:
```python
@solara.component                                                                                                                                               
def Fake():
    print("called Fake")
    sleep(2)
    loading.value = False

@solara.component
def Page():
    with solara.Column():
        solara.Title("Cameo Deployments")
        with solara.Sidebar():
            with solara.Card("Controls"):
                with solara.Column():
                    solara.SliderInt(label="Hours of commits", value=hours)
    solara.Info("Most Recent Commits")

    with solara.Card():
        with solara.Column():
            solara.ProgressLinear(loading.value)
            Fake() 
```
Output upon starting:
```
➜  cameo2_solara solara run sol.py
Solara server is starting at http://localhost:8765
called Fake
called Fake
```

**Comment by maartenbreddels** [comment]
This seems to be a side effect of the AppLayout component  that does a re-render because it finds out you have added a sidebar. This is not something we can fix right now, but I recognize it is not ideal.
I do recommend you to design your component such that it does not matter much that they are getting executed multiple times (e.g. putting heavy work in use_thread)
