### ISSUE TITLE
(Input) components should pass kwargs to underlying vuetify widget

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#50]
To allow passing of things like hints/prefix/class_ etc

I would like to be able to do this:
```python
solara.InputFloat(label="Time start", hint="Start time point.", value=t_min, on_value=set_t_min, class_='ma-2')
```

**Comment by maartenbreddels** [comment]
First, we'd like to have at least CSS classes exposed on all components in solara. Passing kwargs I am not sure about. We could have Reacton produce typed dicts for all components. Then we could add type safe argument passing, e.g.:
solara.InputFloat(..., TextField_kwargs={...}).
If we then change (ipy)vuetify, and the arguments change, you'd get a warning from mypy instead of a silent pass.
Also, if a component is composite, we can have multiple kwargs.
What do you think of this?

**Comment by Jhsmit** [comment]
I'm not sure, I do agree that it makes sense to not have the solara.InputFloat to be exactly the same thing as the veutify equivalent, otherwise there would be no added value, and just passing kwargs would be in this direction.

My current use case is a input form where pydantic does validation, and these errors are shown to the user. It works quite well, and there is not really a problem with just importing veutify from `solara.alias` except perhaps that it might be difficult to find it. 

This is the components which also translates description into tooltips:

```python
class ExperimentMetadata(BaseModel):

    experiment_label: Annotated[str, Field(description="Label for the experiment.", max_length=10)] = "Experiment 1"

    pH: Annotated[float, Field(le=14, ge=2., description="pH value of reaction buffer.")] = 7.0

    temperature: Annotated[float, Field(ge=0., le=100,  title="Reaction temperature", description="Reaction mixture temperature in Celsius.")] = 25.0


```

![image](https://github.com/widgetti/solara/assets/7881506/2e0000c6-f2e6-4549-8aab-7b3e47bc0418)


Currently lives here: https://github.com/Jhsmit/awesome-solara/blob/master/examples/input_form.py

**Comment by maartenbreddels** [comment]
This is now possible with v1.13.0 since we expose error and message in [InputText](https://solara.dev/api/input)
