### ISSUE TITLE
Solara App running on VM is not reachable

### ISSUE THREAD

**Issue by legout** [widgetti/solara#51]
Hi guys,

thanks for this great lib. I´ve already used it some time in jupyter notebooks and running apps on my local machine. However, I am not able to access apps running on my VM (oracle cloud).  All I see is a "solara" spinner and the message "Loading app". I think it´s problem with my firewall configuration. Which ports need to be open for running apps on a virtual machine?

Thanks,
legout

**Comment by maartenbreddels** [comment]
Hi legout,

thanks, that's great to hear!
Solara does need a connection with a WebSocket. I'm wondering if that is the issue. Also, I also noticed an issue with ipykernel 6.22.0, which I just fixed https://github.com/widgetti/solara/commit/08529c3247ccb4b88aec7ba6b91d6a44bbc0485d
But this is not released yet.
So, please downgrade ipykernel, and otherwise, take a look at the javascript dev console if you can see an issue/warning that might help us debug this.

Regards,

Maarten

**Comment by Jhsmit** [comment]
I think i have the same issue - on my local machine my app does not get past the loading spinner. 
It hangs on "Starting WebSocket: ws://localhost:8765/jupyter/api/kernels/solara-id"

This is on a new conda env with ipykernel 6.22.0. 
However, on my other env everything works fine but also uses ipykernel 6.22.0

**Comment by legout** [comment]
I can confirm. Its working after downgrading to ipykernel 6.21.2.
