### ISSUE TITLE
Primary colour used by Solara

### ISSUE THREAD

**Issue by HarryB05** [widgetti/solara#529]
Hi all,  further to my discord query:

I have been using an assets file and this code to change the primary colour of solara to green (see code):

```
vuetifyThemes = {
    light: {
        primary: '#017F36',  // green (from *** logo)
    }
}
```

this is my project structure is attached.  However, recently the primary colour of my solara page has changed back to the default blue.  could this be due to the recent update (1.28.0) where there were changes to themes?  and could someone help resolve this issue?

![image](https://github.com/widgetti/solara/assets/49901436/8c41d9d6-52d4-4730-a5c0-d26991c14d5f)

**Comment by iisakkirotko** [comment]
Hi @HarryB05!

I think this is indeed due to the changes made in 1.28.0. We're looking at the issue, and hope to ship a fix in the next release, which we hope to have out on Monday March 11th, or earlier. I'll let you know when the fix is live on master, in case you want to make use of it before the release.
