### ISSUE TITLE
SideBar css styling & scroll bar disapearing

### ISSUE THREAD

**Issue by BFAGIT** [widgetti/solara#571]
Hey guys,

I've been trying to apply Css styling to the Sidebar to make the scroll bar disapear and appear when we hover over the side bar.

I've tried applying css styling to the sidebar but this doesn't seem possible as no styling options are available for it, I looked and the compoenent definition and the docs.

I was able to apply it to the AppLayout but the custom css styling is then only applied to general frame and not to the sidebar.

Here is a simple example, note that I've only added the css styling for firefox but I observe the same behaviour with other browers to.

```python annotate

import solara

css = """
  .scroll-bar{
    overflow-y: auto; /* Enables vertical scrolling */
    scrollbar-width: none; /* For Firefox */
  }
  .scroll-bar:hover {
    scrollbar-width: auto; /* For Firefox */
  }
    """

@solara.component
def Page():
    with solara.Sidebar():
        with solara.Card("Select Charting options"):
            for i in range(30):
                solara.Info(f"{i}")
    """with solara.AppBar():
        pass"""
        
    with solara.Card("Select Charting options"):
            for i in range(30):
                solara.Info(f"{i}")
                
@solara.component
def Layout(children):
    solara.Style(css)
    solara.AppLayout(children=children, classes=["scroll-bar"])
```
Edit:
I actually looked a bit at the AppLayout and the style feature seems to be a possibility to. The style doesn't seem to  set to the sidebar component. I  looked at the code very quickly.

NB this is definitly not an important request or question just i came accross it and became curios :) 

Thanks again and have a good week :)

**Comment by maartenbreddels** [comment]
For scrolling I usually pick Firefox, if you do "inspect element" you should see sth like:
<img width="2790" alt="image" src="https://github.com/widgetti/solara/assets/1765949/e7302c7c-d54b-447d-a8b5-029e1c9669c2">

Note the purple text on the left "scrolling", which tells you which element does the scrolling. Since that already has a CSS class (`v-navigation-drawer__content`), we can use that:

```python
import solara

css = """
  .v-navigation-drawer__content{
    overflow-y: auto; /* Enables vertical scrolling */
    scrollbar-width: none; /* For Firefox */
  }
  .v-navigation-drawer__content:hover {
    scrollbar-width: auto; /* For Firefox */
  }
    """

@solara.component
def Page():
    with solara.Sidebar():
        with solara.Card("Select Charting options"):
            for i in range(30):
                solara.Info(f"{i}")
    """with solara.AppBar():
        pass"""
        
    with solara.Card("Select Charting options"):
            for i in range(30):
                solara.Info(f"{i}")
                
@solara.component
def Layout(children):
    solara.Style(css)
    solara.AppLayout(children=children, classes=["scroll-bar"])
```
[Run and edit this code snippet at PyCafe](https://app.py.cafe/snippet/solara/v1?c=H4sIALmIAWYAA71WTW_jNhD9K4L2kl1EimTLseNCQNugCxToocACvVTFgqYoi7FEMiRlRwny3_uGUrzZbBe9rZKDOZzP92ZGeoq5rkW8jWVvtPWR0x2zrFKV4s5FZVTF4U9FUXpMFDvKPfNSq6S27CTs589cKy-UfyKNKNJHYZtOn5JxG7HB65-iqw_Rb4rtOuEi3HnJWRc5bnXXSbWPPlxNdpNkx2xykrVvt5HSSgTjj9pGH6UVjX6YtZ__N5ltS3lEc07f-D4n9h3f0bnoSv084ZFyDXgUfFeqFk30J9uLi_fbSfskfTvjln6StUCo893b-1tm64sq_iQ6wX102zJAAhy0oTpcFb-2o6dBijKSKrJMIeQye6sQKpx8_64afdFU8ZN8hqPXlbzO4Bdjfn2ToGEOoV94np5vS_vRqb9-vkvEH2zUg7_grexqK9RLiBc2_NiJCzTy7PILBG_sypcflxHvgIZw5d9VPHVOAj6r-J_38WVsxf2AfukR3mFk1NCbsVK48KOhGZr848yM-UuKU7xtWOfEZSxq6acxiLfeDpB0mh8a2YnbqWVh_C5qmUN7Fs1N0YjVmme7esnXjK03eSF4Vm9uiny32VTqymurWK2T67RIa3HMEzMuExqZhKkxPbVdpcz42N-X5aJIs-hd1CMaZG7wsnsjZHav1SLhTSOTnVQ1OHVluU4Xi7MKWnrYm7Esi7T44kw8GDTC10KlvdhpfSjL63R1lp6Y522t9_8hJQgQbpGn-fliro60p_Iq1TN7qPVJleUyva4UWRGAdMzxj2XFeCu81h2crdJluqxUO_RMyUdBGd6kGQKKnYOR8NDJFySxgnGv4TVPN2QizXgcYIBssnRBIPYUNREP4MhRm-MuS9cUcdL1sgEuOQKQuhv3igHgbLa_G8zohU14J8FxWW7SazIFSVhFewFJBksEHiz24W4JINJFKAfT5YQHp7ZnHYqwVOqSfHrLpO9CEas0L0jU5nmICVqBDXP-ziFVANIz8pjfkEslnE-YGxWXgDZHJlB2SoL3cA4wzgl3bEfLEhkiyjKlcgis-wE-iK10mZP1cJQcXFHsRUBY7TD0PUNdSC2jwlAquS_gHvfArAdFnqGcDG6hMIdRuzPGpD1FxKz3wTkVCbem0x4wJVLh5QGaoEXdAK_nZDcQQZlCACMflJaBa9MxT9nV0kIPuJHwTJC2UF2BWRiLB8ExKAr9CiWCxQxWJOI4URuyOfHwMpnOOeroa3A4pYRrcOD1AfWQiyK4sFhcPqEWPUgARKgWZDd3diI9pniSE9iSwzl6O_QayuGHpGYefGZgDnakQH1FQ5BDqwg4-Jbw22B4KQsIDsIqgbyuiSGYTRuKTHAmz_IhtHvoBsplMI41wAJVhW4bDYD4agCKdEXKfOQdtSUqDs1gRl3j5Ze03psJluDxTNp8P0GEyLUA6AyzHpqFJAd5ksgPr25KCWsFFdQKyS7pJ_OeiKPKQnj6mGgkBBlEGOc1ZBMc1AMo1YzWSUfLNcQM5U8IEZJiXoUY_DDoI-sDTFQJZg89m007ASaPIUpYKoaMgFygdNyHN0EAa5o9LPN5CaHjQ8Q7rP4QP8QJb4yAfhjcO6nu2CJssXB8NbZomjXZ76R-oRVLKqzCF0jJbhW6_b6TXmB7gAhKQxuQ5ZAo0kxzfMXMh3CJCvCBdi4ifv4XwcAIzAIKAAA)

**Comment by BFAGIT** [comment]
Thanks @maartenbreddels.
This seems stupid now that you have given me the solution aahahah. I didn't think of looking the actual web page component with the the developper tools. I will do now 😉.
Thanks
