### ISSUE TITLE
AppBar doesnt show with just Tabs as content

### ISSUE THREAD

**Issue by Jhsmit** [widgetti/solara#634]
```python

@solara.component
def Page():
    solara.Title("title")
    tab_selection = solara.use_reactive(0)

    with solara.AppBar():
        # solara.Button(icon_name="mdi-logout", icon=True)
        with solara.lab.Tabs(value=tab_selection.value, on_value=tab_selection.set, align="center"):
            solara.lab.Tab("Tab 1")
            solara.lab.Tab("Tab 2")

    solara.Card("main")
    solara.Sidebar("sidebar")
```

shows as: 
![image](https://github.com/widgetti/solara/assets/7881506/ad81a69f-024a-43e5-90bd-bb6fc7307620)

with button uncommented:
![image](https://github.com/widgetti/solara/assets/7881506/71362d8f-f5e3-4a58-9e35-8a738b19d036)

**Comment by iisakkirotko** [comment]
Hey @Jhsmit!

This happens because the tabs are the only child to the appbar. What determines whether the appbar gets shown in the Solara code is `show_app_bar`, as defined here https://github.com/widgetti/solara/blob/65a0cfc49be23ff2c894598430764eaa6ce59594/solara/components/applayout.py#L260
So in your case this takes the value `children_appbar`, which only has the tabs in it. However later on tabs get taken out of the `children_appbar`, since they have to be treated specially. https://github.com/widgetti/solara/blob/65a0cfc49be23ff2c894598430764eaa6ce59594/solara/components/applayout.py#L275-L280
This makes `show_app_bar` evaluate as `False` when we want to render it. There was another issue (#584) related to the appbar. I think this week I should take a look at the logic there to see if it can be improved a little bit.

In the meantime, if you need a workaround, defining the tabs by using [routing](https://solara.dev/documentation/advanced/understanding/routing) might be a workaround.

**Comment by iisakkirotko** [comment]
This was fixed in https://github.com/widgetti/solara/pull/656
