### ISSUE TITLE
feature request: Expose `buffer_value` in `ProgressLinear`

### ISSUE THREAD

**Issue by JovanVeljanoski** [widgetti/solara#639]
Is it possible to expose the `buffer_value` param that is available in `ipyvuetify` to be accessible via solara/reacton please?

Also a more general question - is it possible for more of the kwargs not related to style/layout of the components be exposed in solara?

**Comment by maartenbreddels** [comment]
Hi Jovan,

In general, I would like to not expose as many arguments as vuetify (since it's a more low level library), but it's a grey area, and if something is very common, we could add an argument.

See also https://github.com/widgetti/solara/issues/50 https://github.com/widgetti/solara/issues/182 https://github.com/widgetti/solara/issues/154 https://github.com/widgetti/solara/issues/194 https://github.com/widgetti/solara/issues/203

I think the best solution is to have proper docs (see also https://github.com/widgetti/solara/issues/642) and give a clear path forward for when solara components are not enough. E.g:
Pure Solara -> Some ipyvuetify -> vuetify template/react/anywidget


In this case I would say, look at https://github.com/widgetti/solara/blob/master/solara/components/progress.py to see how we use vuetify.

I hope this answers your question.

cheers,

Maarten

**Comment by JovanVeljanoski** [comment]
Hi! 

Yeah I got it. I was a bit confused because I was originally expecting to have to use `ipyvuetify` directly. 
Your example is tied to the usage of  `reacton.ipyvuetify` which from what I can see is a bit of a different thing. 

In general I like the idea proposed in #203. 

Cheers!
