### ISSUE TITLE
Version check crashes with ValueError: invalid literal for int() with base 10: '0a0' for ipykernel 7.0.0a0

### ISSUE THREAD

**Issue by pllim** [widgetti/solara#827]
This line broke when pre-release is available (e.g., `ipykernel==7.0.0a0`):

https://github.com/widgetti/solara/blob/eb8b827a20586a7e1db716ea532b0d686ef94cee/solara/server/kernel.py#L76

```
>   ipykernel_version = tuple(map(int, ipykernel.__version__.split(".")))
E   ValueError: invalid literal for int() with base 10: '0a0'
```

If you switch to, say, `packaging.version.Version` check and take account of pre- or dev releases, then it would guard against such breakage.

Thanks.

**Comment by maartenbreddels** [comment]
Thanks, I didn't realize that was not a good pattern. I refrained from using any Python tooling because it was never clear to me what the best solution is. `packaging` seems to be a very large package that does more than providing packages.

importlib.metadata now seems to be the standard way (says chatgpt), but that is Python >= 3.8.

I do think we can make this more robust, thanks for the issue!

**Comment by paddymul** [comment]
FWIW, `packaging` isn't available in jupyterlite xeus (maybe pyodide too).

**Comment by pllim** [comment]
Anyways, can you please fix this. I really don't care if you use packaging or not, so I will modify the title. Thanks!

**Comment by kecnry** [comment]
Maybe this can be as easy as `ipykernel_version = tuple(map(int, re.split(r'\D+', ipykernel.__version__)[:3]))`?
